In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
train_data1 = pd.read_csv("/content/drive/MyDrive/HAI/train1.csv", sep=";", engine="python")
train_data2 = pd.read_csv("/content/drive/MyDrive/HAI/train2.csv", sep=";", engine="python")

In [ ]:
TRAIN_DF_RAW = pd.concat([train_data1, train_data2], axis=0).reset_index(drop=True)

In [ ]:
test_data1 = pd.read_csv("/content/drive/MyDrive/HAI/test1.csv", sep=";", engine="python")
test_data2 = pd.read_csv("/content/drive/MyDrive/HAI/test2.csv", sep=";", engine="python")

In [ ]:
TEST_DF_RAW = pd.concat([test_data1, test_data2], axis=0).reset_index(drop=True)

In [ ]:
TRAIN_DF_RAW

,time,P1_B2004,P1_B2016,P1_B3004,P1_B3005,P1_B4002,P1_B4005,P1_B400B,P1_B4022,P1_FCV01D,...,P4_ST_FD,P4_ST_LD,P4_ST_PO,P4_ST_PS,P4_ST_PT01,P4_ST_TT01,attack,attack_P1,attack_P2,attack_P3
0,2019-09-11 20:00:00,0.0983,1.0702,399.2321,1110.3986,32.0000,0.0,28.9981,35.7395,0.0,...,-0.0004,330.6568,328.9388,50.9871,9973.0,27629.0,0,0,0,0
1,2019-09-11 20:00:01,0.0983,1.0699,399.2321,1110.3986,32.0000,0.0,29.9914,35.7388,0.0,...,-0.0012,330.2228,329.3728,50.9871,9973.0,27629.0,0,0,0,0
2,2019-09-11 20:00:02,0.0983,1.0703,399.2321,1110.3986,32.0000,0.0,27.0122,35.7399,0.0,...,0.0018,332.0493,329.7526,50.9871,9973.0,27629.0,0,0,0,0
3,2019-09-11 20:00:03,0.0983,1.0719,399.2321,1110.3986,32.0000,0.0,32.9705,35.7452,0.0,...,0.0033,331.5249,331.0547,50.9871,9973.0,27629.0,0,0,0,0
4,2019-09-11 20:00:04,0.0983,1.0710,399.2321,1110.3986,32.0000,0.0,30.9843,35.7422,0.0,...,0.0015,333.1706,331.1631,50.9871,9973.0,27629.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
550795,2019-11-04 14:59:55,0.1001,1.5194,395.3508,1120.8154,29.4139,0.0,33.9638,33.4685,0.0,...,-0.0007,366.9524,362.7749,0.0000,10026.0,27548.0,0,0,0,0
550796,2019-11-04 14:59:56,0.1001,1.5220,395.3508,1120.8154,29.4139,0.0,35.9501,33.4723,0.0,...,-0.0007,365.7950,363.7876,0.0000,10026.0,27549.0,0,0,0,0
550797,2019-11-04 14:59:57,0.1001,1.5235,395.3508,1120.8154,29.4139,0.0,36.9430,33.4833,0.0,...,-0.0003,367.0790,364.0950,0.0000,10026.0,27547.0,0,0,0,0
550798,2019-11-04 14:59:58,0.1001,1.5279,395.3508,1120.8154,29.4139,0.0,35.9501,33.4837,0.0,...,0.0008,367.5492,364.5110,0.0000,10026.0,27551.0,0,0,0,0
550799,2019-11-04 14:59:59,0.1001,1.5281,395.3508,1120.8154,29.4139,0.0,38.9292,33.4811,0.0,...,-0.0010,367.5492,363.7333,0.0000,10026.0,27552.0,0,0,0,0

In [ ]:
del TRAIN_DF_RAW['time']
T_corr = TRAIN_DF_RAW.corr()
T_corr

,P1_B2004,P1_B2016,P1_B3004,P1_B3005,P1_B4002,P1_B4005,P1_B400B,P1_B4022,P1_FCV01D,P1_FCV01Z,...,P4_ST_FD,P4_ST_LD,P4_ST_PO,P4_ST_PS,P4_ST_PT01,P4_ST_TT01,attack,attack_P1,attack_P2,attack_P3
P1_B2004,1.000000,-0.198693,0.110056,-0.129477,-0.106941,-0.015936,-0.015816,-0.072769,-0.010381,-0.010085,...,-0.002018,-0.004715,-0.005211,0.476840,-0.258147,0.016220,0.022419,0.022419,NaN,NaN
P1_B2016,-0.198693,1.000000,0.180849,-0.189421,0.064371,0.111961,0.105540,0.429611,0.093843,0.093005,...,0.063142,0.527837,0.568268,-0.440059,0.764328,-0.085958,-0.078210,-0.078210,NaN,NaN
P1_B3004,0.110056,0.180849,1.000000,-0.012664,0.079402,0.094433,0.095343,0.056695,0.081747,0.081717,...,0.002369,0.005924,0.006654,-0.407224,0.182761,-0.036664,-0.017864,-0.017864,NaN,NaN
P1_B3005,-0.129477,-0.189421,-0.012664,1.000000,-0.161104,-0.089874,-0.091171,-0.104816,-0.067262,-0.066673,...,-0.000659,0.004301,0.004462,0.281513,-0.273947,0.026619,0.018812,0.018812,NaN,NaN
P1_B4002,-0.106941,0.064371,0.079402,-0.161104,1.000000,0.208312,0.208673,0.704495,0.182172,0.181191,...,-0.002809,-0.018033,-0.020049,0.174521,0.088000,0.157604,0.039609,0.039609,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P4_ST_TT01,0.016220,-0.085958,-0.036664,0.026619,0.157604,-0.500815,-0.462307,0.116730,-0.487634,-0.486088,...,0.000317,0.002693,0.002199,0.140201,-0.107652,1.000000,-0.013456,-0.013456,NaN,NaN
attack,0.022419,-0.078210,-0.017864,0.018812,0.039609,0.008276,0.005427,0.015123,0.015702,0.015513,...,-0.000607,-0.016200,-0.019144,-0.032274,-0.014017,-0.013456,1.000000,1.000000,NaN,NaN
attack_P1,0.022419,-0.078210,-0.017864,0.018812,0.039609,0.008276,0.005427,0.015123,0.015702,0.015513,...,-0.000607,-0.016200,-0.019144,-0.032274,-0.014017,-0.013456,1.000000,1.000000,NaN,NaN
attack_P2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
attack_P3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:

for col in TRAIN_DF_RAW.columns:
  print("========================================")
  print(TRAIN_DF_RAW.corr()[col][TRAIN_DF_RAW.corr()[col] > 0.7])
  print("========================================")

========================================
P1_B2004    1.0
Name: P1_B2004, dtype: float64
========================================
========================================
P1_B2016      1.000000
P1_FT01       0.702690
P1_PCV01D     0.737922
P1_PCV01Z     0.731349
P1_PCV02Z     0.789629
P1_PIT01      0.780463
P4_ST_PT01    0.764328
Name: P1_B2016, dtype: float64
========================================
========================================
P1_B3004    1.000000
P1_LIT01    0.984756
Name: P1_B3004, dtype: float64
========================================
========================================
P1_B3005    1.000000
P1_FT03     0.989579
P1_FT03Z    0.990196
Name: P1_B3005, dtype: float64
========================================
========================================
P1_B4002    1.000000
P1_B4022    0.704495
Name: P1_B4002, dtype: float64
========================================
========================================
P1_B4005     1.000000
P1_B400B     0.989952
P1_FCV01D    0.930823
P1_FCV01Z    0.930080
P1_FT02      0.978017
P1_FT02Z     0.990071
Name: P1_B4005, dtype: float64
========================================
========================================
P1_B4005     0.989952
P1_B400B     1.000000
P1_FCV01D    0.911678
P1_FCV01Z    0.911763
P1_FT02      0.978204
P1_FT02Z     0.999263
Name: P1_B400B, dtype: float64
========================================
========================================
P1_B4002    0.704495
P1_B4022    1.000000
Name: P1_B4022, dtype: float64
========================================
========================================
P1_B4005     0.930823
P1_B400B     0.911678
P1_FCV01D    1.000000
P1_FCV01Z    0.999459
P1_FT02      0.951627
P1_FT02Z     0.911454
Name: P1_FCV01D, dtype: float64
========================================
========================================
P1_B4005     0.930080
P1_B400B     0.911763
P1_FCV01D    0.999459
P1_FCV01Z    1.000000
P1_FT02      0.952611
P1_FT02Z     0.912381
Name: P1_FCV01Z, dtype: float64
========================================
========================================
P1_FCV02D    1.000000
P1_FCV02Z    0.873336
Name: P1_FCV02D, dtype: float64
========================================
========================================
P1_FCV02D    0.873336
P1_FCV02Z    1.000000
Name: P1_FCV02Z, dtype: float64
========================================
========================================
P1_FCV03D    1.000000
P1_FCV03Z    0.962983
Name: P1_FCV03D, dtype: float64
========================================
========================================
P1_FCV03D    0.962983
P1_FCV03Z    1.000000
Name: P1_FCV03Z, dtype: float64
========================================
========================================
P1_B2016     0.702690
P1_FT01      1.000000
P1_FT01Z     0.967195
P1_PCV01D    0.793155
P1_PCV01Z    0.792863
P1_PCV02Z    0.800838
Name: P1_FT01, dtype: float64
========================================
========================================
P1_FT01      0.967195
P1_FT01Z     1.000000
P1_PCV01D    0.742612
P1_PCV01Z    0.742267
P1_PCV02Z    0.752136
Name: P1_FT01Z, dtype: float64
========================================
========================================
P1_B4005     0.978017
P1_B400B     0.978204
P1_FCV01D    0.951627
P1_FCV01Z    0.952611
P1_FT02      1.000000
P1_FT02Z     0.979012
Name: P1_FT02, dtype: float64
========================================
========================================
P1_B4005     0.990071
P1_B400B     0.999263
P1_FCV01D    0.911454
P1_FCV01Z    0.912381
P1_FT02      0.979012
P1_FT02Z     1.000000
Name: P1_FT02Z, dtype: float64
========================================
========================================
P1_B3005    0.989579
P1_FT03     1.000000
P1_FT03Z    0.994318
Name: P1_FT03, dtype: float64
========================================
========================================
P1_B3005    0.990196
P1_FT03     0.994318
P1_FT03Z    1.000000
Name: P1_FT03Z, dtype: float64
========================================
========================================
P1_LCV01D    1.000000
P1_LCV01Z    0.989826
P2_SD01      0.812361
P2_SIT01     0.807928
Name: P1_LCV01D, dtype: float64
========================================
========================================
P1_LCV01D    0.989826
P1_LCV01Z    1.000000
P2_SD01      0.812724
P2_SIT01     0.808169
Name: P1_LCV01Z, dtype: float64
========================================
========================================
P1_B3004    0.984756
P1_LIT01    1.000000
Name: P1_LIT01, dtype: float64
========================================
========================================
P1_B2016      0.737922
P1_FT01       0.793155
P1_FT01Z      0.742612
P1_PCV01D     1.000000
P1_PCV01Z     0.999767
P1_PCV02Z     0.835083
P1_PIT01      0.764334
P4_ST_PT01    0.738489
Name: P1_PCV01D, dtype: float64
========================================
========================================
P1_B2016      0.731349
P1_FT01       0.792863
P1_FT01Z      0.742267
P1_PCV01D     0.999767
P1_PCV01Z     1.000000
P1_PCV02Z     0.836241
P1_PIT01      0.767988
P4_ST_PT01    0.742170
Name: P1_PCV01Z, dtype: float64
========================================
========================================
Series([], Name: P1_PCV02D, dtype: float64)
========================================
========================================
P1_B2016      0.789629
P1_FT01       0.800838
P1_FT01Z      0.752136
P1_PCV01D     0.835083
P1_PCV01Z     0.836241
P1_PCV02Z     1.000000
P1_PIT01      0.893919
P4_ST_PT01    0.868340
Name: P1_PCV02Z, dtype: float64
========================================
========================================
P1_B2016      0.780463
P1_PCV01D     0.764334
P1_PCV01Z     0.767988
P1_PCV02Z     0.893919
P1_PIT01      1.000000
P4_ST_PT01    0.986635
Name: P1_PIT01, dtype: float64
========================================
========================================
P1_PIT02    1.0
Name: P1_PIT02, dtype: float64
========================================
========================================
P1_TIT01    1.000000
P1_TIT02    0.816413
Name: P1_TIT01, dtype: float64
========================================
========================================
P1_TIT01    0.816413
P1_TIT02    1.000000
Name: P1_TIT02, dtype: float64
========================================
========================================
P2_24Vdc    1.0
Name: P2_24Vdc, dtype: float64
========================================
========================================
Series([], Name: P2_Auto, dtype: float64)
========================================
========================================
Series([], Name: P2_Emgy, dtype: float64)
========================================
========================================
Series([], Name: P2_On, dtype: float64)
========================================
========================================
P1_LCV01D    0.812361
P1_LCV01Z    0.812724
P2_SD01      1.000000
P2_SIT01     0.996314
P3_LT01      0.700173
Name: P2_SD01, dtype: float64
========================================
========================================
P1_LCV01D    0.807928
P1_LCV01Z    0.808169
P2_SD01      0.996314
P2_SIT01     1.000000
Name: P2_SIT01, dtype: float64
========================================
========================================
Series([], Name: P2_TripEx, dtype: float64)
========================================
========================================
P2_VT01e    1.0
Name: P2_VT01e, dtype: float64
========================================
========================================
P2_VXT02    1.000000
P2_VXT03    0.817677
Name: P2_VXT02, dtype: float64
========================================
========================================
P2_VXT02    0.817677
P2_VXT03    1.000000
Name: P2_VXT03, dtype: float64
========================================
========================================
P2_VYT02    1.000000
P2_VYT03    0.728922
Name: P2_VYT02, dtype: float64
========================================
========================================
P2_VYT02    0.728922
P2_VYT03    1.000000
Name: P2_VYT03, dtype: float64
========================================
========================================
P3_LCP01D    1.0
Name: P3_LCP01D, dtype: float64
========================================
========================================
P3_LCV01D    1.000000
P4_HT_LD     0.975079
P4_HT_PO     0.998716
P4_LD        0.862465
Name: P3_LCV01D, dtype: float64
========================================
========================================
Series([], Name: P3_LH, dtype: float64)
========================================
========================================
Series([], Name: P3_LL, dtype: float64)
========================================
========================================
P2_SD01    0.700173
P3_LT01    1.000000
Name: P3_LT01, dtype: float64
========================================
========================================
P4_HT_FD    1.0
Name: P4_HT_FD, dtype: float64
========================================
========================================
P3_LCV01D    0.975079
P4_HT_LD     1.000000
P4_HT_PO     0.966922
P4_LD        0.891015
Name: P4_HT_LD, dtype: float64
========================================
========================================
P3_LCV01D    0.998716
P4_HT_LD     0.966922
P4_HT_PO     1.000000
P4_LD        0.851945
Name: P4_HT_PO, dtype: float64
========================================
========================================
Series([], Name: P4_HT_PS, dtype: float64)
========================================
========================================
P3_LCV01D    0.862465
P4_HT_LD     0.891015
P4_HT_PO     0.851945
P4_LD        1.000000
P4_ST_LD     0.896803
P4_ST_PO     0.924455
Name: P4_LD, dtype: float64
========================================
========================================
P4_ST_FD    1.0
Name: P4_ST_FD, dtype: float64
========================================
========================================
P4_LD       0.896803
P4_ST_LD    1.000000
P4_ST_PO    0.949736
Name: P4_ST_LD, dtype: float64
========================================
========================================
P4_LD       0.924455
P4_ST_LD    0.949736
P4_ST_PO    1.000000
Name: P4_ST_PO, dtype: float64
========================================
========================================
P4_ST_PS    1.0
Name: P4_ST_PS, dtype: float64
========================================
========================================
P1_B2016      0.764328
P1_PCV01D     0.738489
P1_PCV01Z     0.742170
P1_PCV02Z     0.868340
P1_PIT01      0.986635
P4_ST_PT01    1.000000
Name: P4_ST_PT01, dtype: float64
========================================
========================================
P4_ST_TT01    1.0
Name: P4_ST_TT01, dtype: float64
========================================
========================================
attack       1.0
attack_P1    1.0
Name: attack, dtype: float64
========================================
========================================
attack       1.0
attack_P1    1.0
Name: attack_P1, dtype: float64
========================================
========================================
Series([], Name: attack_P2, dtype: float64)
========================================
========================================
Series([], Name: attack_P3, dtype: float64)
========================================

In [ ]:
del TEST_DF_RAW['time']

In [ ]:
a_val = TEST_DF_RAW[TEST_DF_RAW['attack'] == 1]
a_normal = TEST_DF_RAW[TEST_DF_RAW['attack'] == 0]

In [ ]:
for col in TEST_DF_RAW.columns:
  print("========================================")
  print(a_val.corr()[col][a_val.corr()[col] > 0.7])
  print("========================================")

========================================
P1_B2004    1.0
Name: P1_B2004, dtype: float64
========================================
========================================
P1_B2016    1.000000
P4_LD       0.902282
P4_ST_LD    0.907406
P4_ST_PO    0.971133
Name: P1_B2016, dtype: float64
========================================
========================================
P1_B3004    1.0
Name: P1_B3004, dtype: float64
========================================
========================================
P1_B3005    1.0
Name: P1_B3005, dtype: float64
========================================
========================================
P1_B4002      1.000000
P1_B4022      0.957234
P1_TIT01      0.734124
P4_ST_TT01    0.746628
Name: P1_B4002, dtype: float64
========================================
========================================
P1_B4005     1.000000
P1_B400B     0.987889
P1_FCV01D    0.939433
P1_FCV01Z    0.938193
P1_FT02      0.969509
P1_FT02Z     0.988014
Name: P1_B4005, dtype: float64
========================================
========================================
P1_B4005     0.987889
P1_B400B     1.000000
P1_FCV01D    0.918828
P1_FCV01Z    0.918474
P1_FT02      0.973400
P1_FT02Z     0.999032
Name: P1_B400B, dtype: float64
========================================
========================================
P1_B4002      0.957234
P1_B4022      1.000000
P4_ST_TT01    0.713048
Name: P1_B4022, dtype: float64
========================================
========================================
P1_B4005     0.939433
P1_B400B     0.918828
P1_FCV01D    1.000000
P1_FCV01Z    0.999297
P1_FT02      0.956903
P1_FT02Z     0.918511
Name: P1_FCV01D, dtype: float64
========================================
========================================
P1_B4005     0.938193
P1_B400B     0.918474
P1_FCV01D    0.999297
P1_FCV01Z    1.000000
P1_FT02      0.958341
P1_FT02Z     0.919289
Name: P1_FCV01Z, dtype: float64
========================================
========================================
P1_FCV02D    1.000000
P1_FCV02Z    0.878073
Name: P1_FCV02D, dtype: float64
========================================
========================================
P1_FCV02D    0.878073
P1_FCV02Z    1.000000
Name: P1_FCV02Z, dtype: float64
========================================
========================================
P1_FCV03D    1.000000
P1_FCV03Z    0.964127
Name: P1_FCV03D, dtype: float64
========================================
========================================
P1_FCV03D    0.964127
P1_FCV03Z    1.000000
Name: P1_FCV03Z, dtype: float64
========================================
========================================
P1_FT01     1.000000
P1_FT01Z    0.920545
Name: P1_FT01, dtype: float64
========================================
========================================
P1_FT01     0.920545
P1_FT01Z    1.000000
Name: P1_FT01Z, dtype: float64
========================================
========================================
P1_B4005     0.969509
P1_B400B     0.973400
P1_FCV01D    0.956903
P1_FCV01Z    0.958341
P1_FT02      1.000000
P1_FT02Z     0.974323
Name: P1_FT02, dtype: float64
========================================
========================================
P1_B4005     0.988014
P1_B400B     0.999032
P1_FCV01D    0.918511
P1_FCV01Z    0.919289
P1_FT02      0.974323
P1_FT02Z     1.000000
Name: P1_FT02Z, dtype: float64
========================================
========================================
P1_FT03    1.0
Name: P1_FT03, dtype: float64
========================================
========================================
P1_FT03Z    1.0
Name: P1_FT03Z, dtype: float64
========================================
========================================
P1_LCV01D    1.000000
P1_LCV01Z    0.957772
Name: P1_LCV01D, dtype: float64
========================================
========================================
P1_LCV01D    0.957772
P1_LCV01Z    1.000000
Name: P1_LCV01Z, dtype: float64
========================================
========================================
P1_LIT01    1.0
Name: P1_LIT01, dtype: float64
========================================
========================================
P1_PCV01D    1.000000
P1_PCV01Z    0.999062
Name: P1_PCV01D, dtype: float64
========================================
========================================
P1_PCV01D    0.999062
P1_PCV01Z    1.000000
Name: P1_PCV01Z, dtype: float64
========================================
========================================
P1_PCV02D    1.000000
P1_PCV02Z    0.970905
Name: P1_PCV02D, dtype: float64
========================================
========================================
P1_PCV02D    0.970905
P1_PCV02Z    1.000000
Name: P1_PCV02Z, dtype: float64
========================================
========================================
P1_PIT01    1.0
Name: P1_PIT01, dtype: float64
========================================
========================================
P1_PIT02    1.0
Name: P1_PIT02, dtype: float64
========================================
========================================
P1_B4002      0.734124
P1_TIT01      1.000000
P4_ST_TT01    0.865182
Name: P1_TIT01, dtype: float64
========================================
========================================
P1_TIT02    1.0
Name: P1_TIT02, dtype: float64
========================================
========================================
P2_24Vdc    1.0
Name: P2_24Vdc, dtype: float64
========================================
========================================
Series([], Name: P2_Auto, dtype: float64)
========================================
========================================
Series([], Name: P2_Emgy, dtype: float64)
========================================
========================================
Series([], Name: P2_On, dtype: float64)
========================================
========================================
Series([], Name: P2_SD01, dtype: float64)
========================================
========================================
P2_SIT01    1.0
Name: P2_SIT01, dtype: float64
========================================
========================================
Series([], Name: P2_TripEx, dtype: float64)
========================================
========================================
P2_VT01e    1.0
Name: P2_VT01e, dtype: float64
========================================
========================================
P2_VXT02    1.000000
P2_VXT03    0.710627
Name: P2_VXT02, dtype: float64
========================================
========================================
P2_VXT02    0.710627
P2_VXT03    1.000000
P2_VYT02    0.753881
Name: P2_VXT03, dtype: float64
========================================
========================================
P2_VXT03    0.753881
P2_VYT02    1.000000
Name: P2_VYT02, dtype: float64
========================================
========================================
P2_VYT03    1.0
Name: P2_VYT03, dtype: float64
========================================
========================================
P3_LCP01D    1.0
Name: P3_LCP01D, dtype: float64
========================================
========================================
P3_LCV01D    1.000000
P4_HT_LD     0.921089
P4_HT_PO     0.940913
P4_LD        0.812866
Name: P3_LCV01D, dtype: float64
========================================
========================================
Series([], Name: P3_LH, dtype: float64)
========================================
========================================
Series([], Name: P3_LL, dtype: float64)
========================================
========================================
P3_LT01    1.0
Name: P3_LT01, dtype: float64
========================================
========================================
P4_HT_FD    1.0
Name: P4_HT_FD, dtype: float64
========================================
========================================
P3_LCV01D    0.921089
P4_HT_LD     1.000000
P4_HT_PO     0.966291
P4_LD        0.886944
Name: P4_HT_LD, dtype: float64
========================================
========================================
P3_LCV01D    0.940913
P4_HT_LD     0.966291
P4_HT_PO     1.000000
P4_LD        0.850795
Name: P4_HT_PO, dtype: float64
========================================
========================================
Series([], Name: P4_HT_PS, dtype: float64)
========================================
========================================
P1_B2016     0.902282
P3_LCV01D    0.812866
P4_HT_LD     0.886944
P4_HT_PO     0.850795
P4_LD        1.000000
P4_ST_LD     0.888865
P4_ST_PO     0.919275
Name: P4_LD, dtype: float64
========================================
========================================
P4_ST_FD    1.0
Name: P4_ST_FD, dtype: float64
========================================
========================================
P1_B2016    0.907406
P4_LD       0.888865
P4_ST_LD    1.000000
P4_ST_PO    0.952153
Name: P4_ST_LD, dtype: float64
========================================
========================================
P1_B2016    0.971133
P4_LD       0.919275
P4_ST_LD    0.952153
P4_ST_PO    1.000000
Name: P4_ST_PO, dtype: float64
========================================
========================================
Series([], Name: P4_ST_PS, dtype: float64)
========================================
========================================
P4_ST_PT01    1.0
Name: P4_ST_PT01, dtype: float64
========================================
========================================
P1_B4002      0.746628
P1_B4022      0.713048
P1_TIT01      0.865182
P4_ST_TT01    1.000000
Name: P4_ST_TT01, dtype: float64
========================================
========================================
Series([], Name: attack, dtype: float64)
========================================
========================================
attack_P1    1.0
Name: attack_P1, dtype: float64
========================================
========================================
attack_P2    1.0
Name: attack_P2, dtype: float64
========================================
========================================
attack_P3    1.0
Name: attack_P3, dtype: float64
========================================

In [ ]:
for col in TEST_DF_RAW.columns:
  print("========================================")
  print(a_normal.corr()[col][a_normal.corr()[col] > 0.7])
  print("========================================")

========================================
P1_B2004    1.0
Name: P1_B2004, dtype: float64
========================================
========================================
P1_B2016    1.000000
P4_LD       0.876187
P4_ST_LD    0.888846
P4_ST_PO    0.958851
Name: P1_B2016, dtype: float64
========================================
========================================
P1_B3004    1.000000
P1_LIT01    0.974554
Name: P1_B3004, dtype: float64
========================================
========================================
P1_B3005     1.000000
P1_FCV03D    0.774407
P1_FCV03Z    0.775847
P1_FT01      0.796347
P1_FT01Z     0.824025
P1_FT03      0.973147
P1_FT03Z     0.967023
P1_LCV01D    0.819764
P1_LCV01Z    0.818036
Name: P1_B3005, dtype: float64
========================================
========================================
P1_B4002    1.00000
P1_B4022    0.83863
Name: P1_B4002, dtype: float64
========================================
========================================
P1_B4005     1.000000
P1_B400B     0.988927
P1_FCV01D    0.927832
P1_FCV01Z    0.927106
P1_FT02      0.977102
P1_FT02Z     0.989051
Name: P1_B4005, dtype: float64
========================================
========================================
P1_B4005     0.988927
P1_B400B     1.000000
P1_FCV01D    0.908145
P1_FCV01Z    0.908377
P1_FT02      0.978032
P1_FT02Z     0.999289
Name: P1_B400B, dtype: float64
========================================
========================================
P1_B4002    0.83863
P1_B4022    1.00000
Name: P1_B4022, dtype: float64
========================================
========================================
P1_B4005     0.927832
P1_B400B     0.908145
P1_FCV01D    1.000000
P1_FCV01Z    0.999469
P1_FT02      0.949733
P1_FT02Z     0.907928
Name: P1_FCV01D, dtype: float64
========================================
========================================
P1_B4005     0.927106
P1_B400B     0.908377
P1_FCV01D    0.999469
P1_FCV01Z    1.000000
P1_FT02      0.950726
P1_FT02Z     0.908975
Name: P1_FCV01Z, dtype: float64
========================================
========================================
P1_FCV02D    1.00000
P1_FCV02Z    0.86843
Name: P1_FCV02D, dtype: float64
========================================
========================================
P1_FCV02D    0.86843
P1_FCV02Z    1.00000
Name: P1_FCV02Z, dtype: float64
========================================
========================================
P1_B3005     0.774407
P1_FCV03D    1.000000
P1_FCV03Z    0.948397
P1_FT03      0.736700
P1_FT03Z     0.717661
Name: P1_FCV03D, dtype: float64
========================================
========================================
P1_B3005     0.775847
P1_FCV03D    0.948397
P1_FCV03Z    1.000000
P1_FT03      0.800444
P1_FT03Z     0.787062
Name: P1_FCV03Z, dtype: float64
========================================
========================================
P1_B3005     0.796347
P1_FT01      1.000000
P1_FT01Z     0.922307
P1_FT03      0.817047
P1_FT03Z     0.803301
P1_LCV01D    0.869170
P1_LCV01Z    0.915272
Name: P1_FT01, dtype: float64
========================================
========================================
P1_B3005     0.824025
P1_FT01      0.922307
P1_FT01Z     1.000000
P1_FT03      0.846091
P1_FT03Z     0.852978
P1_LCV01D    0.764859
P1_LCV01Z    0.839359
Name: P1_FT01Z, dtype: float64
========================================
========================================
P1_B4005     0.977102
P1_B400B     0.978032
P1_FCV01D    0.949733
P1_FCV01Z    0.950726
P1_FT02      1.000000
P1_FT02Z     0.978820
Name: P1_FT02, dtype: float64
========================================
========================================
P1_B4005     0.989051
P1_B400B     0.999289
P1_FCV01D    0.907928
P1_FCV01Z    0.908975
P1_FT02      0.978820
P1_FT02Z     1.000000
Name: P1_FT02Z, dtype: float64
========================================
========================================
P1_B3005     0.973147
P1_FCV03D    0.736700
P1_FCV03Z    0.800444
P1_FT01      0.817047
P1_FT01Z     0.846091
P1_FT03      1.000000
P1_FT03Z     0.988891
P1_LCV01D    0.788240
P1_LCV01Z    0.841216
Name: P1_FT03, dtype: float64
========================================
========================================
P1_B3005     0.967023
P1_FCV03D    0.717661
P1_FCV03Z    0.787062
P1_FT01      0.803301
P1_FT01Z     0.852978
P1_FT03      0.988891
P1_FT03Z     1.000000
P1_LCV01D    0.759511
P1_LCV01Z    0.823336
Name: P1_FT03Z, dtype: float64
========================================
========================================
P1_B3005     0.819764
P1_FT01      0.869170
P1_FT01Z     0.764859
P1_FT03      0.788240
P1_FT03Z     0.759511
P1_LCV01D    1.000000
P1_LCV01Z    0.954516
Name: P1_LCV01D, dtype: float64
========================================
========================================
P1_B3005     0.818036
P1_FT01      0.915272
P1_FT01Z     0.839359
P1_FT03      0.841216
P1_FT03Z     0.823336
P1_LCV01D    0.954516
P1_LCV01Z    1.000000
Name: P1_LCV01Z, dtype: float64
========================================
========================================
P1_B3004    0.974554
P1_LIT01    1.000000
Name: P1_LIT01, dtype: float64
========================================
========================================
P1_PCV01D    1.000000
P1_PCV01Z    0.999677
Name: P1_PCV01D, dtype: float64
========================================
========================================
P1_PCV01D    0.999677
P1_PCV01Z    1.000000
Name: P1_PCV01Z, dtype: float64
========================================
========================================
Series([], Name: P1_PCV02D, dtype: float64)
========================================
========================================
P1_PCV02Z    1.0
Name: P1_PCV02Z, dtype: float64
========================================
========================================
P1_PIT01      1.000000
P4_ST_PT01    0.931182
Name: P1_PIT01, dtype: float64
========================================
========================================
P1_PIT02    1.0
Name: P1_PIT02, dtype: float64
========================================
========================================
P1_TIT01      1.000000
P1_TIT02      0.721291
P4_ST_TT01    0.874725
Name: P1_TIT01, dtype: float64
========================================
========================================
P1_TIT01    0.721291
P1_TIT02    1.000000
Name: P1_TIT02, dtype: float64
========================================
========================================
P2_24Vdc    1.0
Name: P2_24Vdc, dtype: float64
========================================
========================================
Series([], Name: P2_Auto, dtype: float64)
========================================
========================================
Series([], Name: P2_Emgy, dtype: float64)
========================================
========================================
Series([], Name: P2_On, dtype: float64)
========================================
========================================
Series([], Name: P2_SD01, dtype: float64)
========================================
========================================
P2_SIT01    1.0
Name: P2_SIT01, dtype: float64
========================================
========================================
Series([], Name: P2_TripEx, dtype: float64)
========================================
========================================
P2_VT01e    1.0
Name: P2_VT01e, dtype: float64
========================================
========================================
P2_VXT02    1.000000
P2_VXT03    0.774231
Name: P2_VXT02, dtype: float64
========================================
========================================
P2_VXT02    0.774231
P2_VXT03    1.000000
Name: P2_VXT03, dtype: float64
========================================
========================================
P2_VYT02    1.000000
P2_VYT03    0.727247
Name: P2_VYT02, dtype: float64
========================================
========================================
P2_VYT02    0.727247
P2_VYT03    1.000000
Name: P2_VYT03, dtype: float64
========================================
========================================
P3_LCP01D    1.0
Name: P3_LCP01D, dtype: float64
========================================
========================================
P3_LCV01D    1.000000
P4_HT_LD     0.975000
P4_HT_PO     0.998932
P4_LD        0.857845
Name: P3_LCV01D, dtype: float64
========================================
========================================
Series([], Name: P3_LH, dtype: float64)
========================================
========================================
Series([], Name: P3_LL, dtype: float64)
========================================
========================================
P3_LT01    1.0
Name: P3_LT01, dtype: float64
========================================
========================================
P4_HT_FD    1.0
Name: P4_HT_FD, dtype: float64
========================================
========================================
P3_LCV01D    0.975000
P4_HT_LD     1.000000
P4_HT_PO     0.966664
P4_LD        0.887550
Name: P4_HT_LD, dtype: float64
========================================
========================================
P3_LCV01D    0.998932
P4_HT_LD     0.966664
P4_HT_PO     1.000000
P4_LD        0.846830
Name: P4_HT_PO, dtype: float64
========================================
========================================
Series([], Name: P4_HT_PS, dtype: float64)
========================================
========================================
P1_B2016     0.876187
P3_LCV01D    0.857845
P4_HT_LD     0.887550
P4_HT_PO     0.846830
P4_LD        1.000000
P4_ST_LD     0.890512
P4_ST_PO     0.918946
Name: P4_LD, dtype: float64
========================================
========================================
P4_ST_FD    1.0
Name: P4_ST_FD, dtype: float64
========================================
========================================
P1_B2016    0.888846
P4_LD       0.890512
P4_ST_LD    1.000000
P4_ST_PO    0.948465
Name: P4_ST_LD, dtype: float64
========================================
========================================
P1_B2016    0.958851
P4_LD       0.918946
P4_ST_LD    0.948465
P4_ST_PO    1.000000
Name: P4_ST_PO, dtype: float64
========================================
========================================
P4_ST_PS    1.0
Name: P4_ST_PS, dtype: float64
========================================
========================================
P1_PIT01      0.931182
P4_ST_PT01    1.000000
Name: P4_ST_PT01, dtype: float64
========================================
========================================
P1_TIT01      0.874725
P4_ST_TT01    1.000000
Name: P4_ST_TT01, dtype: float64
========================================
========================================
Series([], Name: attack, dtype: float64)
========================================
========================================
Series([], Name: attack_P1, dtype: float64)
========================================
========================================
Series([], Name: attack_P2, dtype: float64)
========================================
========================================
Series([], Name: attack_P3, dtype: float64)
========================================